# Generated by Django 4.2.7 on 2025-11-13 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento solo deben ser numeros', regex='^\\d{7,8}$')], verbose_name='nuemro de dni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El telefono solo puede contener numeros y los siguientes caracteres: +, -, ( ,', regex='^[0-9+()-]+$')], verbose_name='Telefono')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx'), models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx')],
            },
        ),
    ]
